# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    commands:
      # variable
      - REPOSITORY_URI=839162139045.dkr.ecr.us-east-2.amazonaws.com/time_app-repository
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - CONTAINER=sta-time-app-container
      - echo $AWS_DEFAULT_REGION
      # Installation
      - echo Entered the install phase...
      - apt-get update -y
      - apt-get install -y software-properties-common
      - add-apt-repository ppa:openjdk-r/ppa
      - apt-get update -y
      - apt-get install nodejs -y
      - apt-get install npm -y
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - nodejs -v
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Entered the post_build phase...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
    - index.js
    - package.json
    - package-lock.json
    - node_modules/*
    - Dockerfile
    - buildspec.yml